[package]
name = "diesel_ltree"
version = "0.1.0"
authors = ["Ashe Connor <ashe@kivikakk.ee>"]
description = "Adds support for the PostgreSQL ltree extension to Diesel"
license = "MIT"
categories = ["database"]
readme = "README.md"

[dependencies]
diesel = { version = "0.16.0", features = ["postgres"] }