[package]
name = "diesel_ltree"
version = "0.1.3"
authors = ["Ashe Connor <ashe@kivikakk.ee>"]
description = "Adds support for the PostgreSQL ltree extension to Diesel"
license = "MIT"
categories = ["database"]
readme = "README.md"
repository = "https://github.com/kivikakk/diesel_ltree"

[dependencies]
diesel = { version = "0.16.0", features = ["postgres"] }

[build-dependencies]
dotenv = "0.10"
diesel = { version = "0.16.0", features = ["postgres"] }

[dev-dependencies]
dotenv = "0.10"
diesel_codegen = "0.16.0"
